// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfigPanel: typeof import('./src/components/ConfigPanel.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    GameWall: typeof import('./src/components/GameWall.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadowGamewall: typeof import('./src/components/shadowGamewall.vue')['default']
  }
}

export {}
